name: Build Aplikasi Go di Windows Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    # Menggunakan label 'self-hosted' agar job dijalankan di runner lokal Anda
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Jalankan Aplikasi Go
        # Perintah ini sekarang akan dijalankan di direktori root repository
        # yang sudah di-checkout oleh runner.
        run: |
          go mod tidy
          go run main.go

      - name: Pesan Sukses
        run: echo "Aplikasi Go berhasil dijalankan di GitHub Actions dengan runner lokal."
