name: Build Aplikasi Go di Windows Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    # Menggunakan label 'self-hosted' agar job dijalankan di runner lokal Anda
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Lakukan Build Aplikasi Go
        # Perintah ini akan mengompilasi kode Anda menjadi file biner
        # File ini akan dinamai 'pk-fiber.exe'
        run: |
          go mod tidy
          go build -o pk-fiber.exe

      - name: Pesan Sukses
        run: echo "Build aplikasi Go berhasil dijalankan di GitHub Actions."
